%% Systems Lab: Systems of ODEs in MATLAB
%
% In this lab, you will write your own ODE system solver for the Heun method 
% (or Improved Euler method), and compare its results to those of |ode45|.
%
% You will also learn how to save images in MATLAB.
% 
% Opening the m-file lab4.m in the MATLAB editor, step through each
% part using cell mode to see the results.  Compare the output with the
% PDF, which was generated from this m-file.
%
% There are four (4) exercises in this lab that are to be handed in at the
% end of the lab.  Write your solutions in the template, including
% appropriate descriptions in each step. Save the m-files and the pdf-file 
% for Exercise 4 and submit them online using Blackboard.
%
% MAT292, Fall 2015, Sousa

%% Student Information
%
%  Student Name: David Wang
%
%  Student Number: 1001XXXXXX
%

%% Exercise 1
%
% Objective: Write your own ODE system solver using the Heun/Improved Euler 
% Method and compare it to |ode45|.
%
% Details: Consider the system of 2 ODEs:
%
%  |x1'=f(t,x1,x2)|
%  |x2'=g(t,x1,x2)|
%
% This m-file should be a function which accepts as variables 
% (t0,tN,x0,h), where t0 and tN are the start and end points of the 
% interval on which to solve the ODE, h is the stepsize, and x0 is a vector 
% for the initial condition of the system of ODEs |x(t0)=x0|.
% You may also want to pass the functions into the ODE the way |ode45| 
% does (check MATLAB labs 2 and 3).
%
% Your m-file should return a matrix where the first row has the
% approximation for |x1| and the second row has the approximation for
% |x2|.
% 
% Note: you will need to use a loop to do this exercise.  
% You will also need to recall the Heun/Improved Euler algorithm learned in lectures.  
%

% Function copied from lecture/lab3 with adjustments for a 2 system

% function IEM_two = IE(f1, f2, t0, tN, x0, h) 
%
% Intialize arrays
% N = floor((tN-t0)/h); 
% Nsol = size(x0, 1);
%
% For loop to go through all N vector solutions
%    
% Initialize arrays
%     x = x0;
%     t(1) = t0;
%     IE_out.t = zeros(1, N);
%     IE_out.y = zeros(1, N);
%
% For loop to go through all N IE solutions
%     for n = 1:N
%  
%         t(n+1) = t(n) + h;
%
%         x(1, n + 1) = x(1, n) + f1(t(n), x(1, n), x(2, n)) * h;
%         x(2, n + 1) = x(2, n) + f2(t(n), x(1, n), x(2, n)) * h;
%
% y(n+1) sub into defined EM for IEM 
%         x(1, n + 1) = x(1, n) + ((f1(t(n),x(1, n), x(2, n)) + f1(t(n+1), x(1, n+1), x(2, n+1))) / 2) * h;
%         x(2, n + 1) = x(2, n) + ((f2(t(n),x(1, n), x(2, n)) + f2(t(n+1), x(1, n+1), x(2, n+1))) / 2) * h;  
%    end
%
% Value assignment[NEW]
% IEM_two.t = t;
% IEM_two.y = x; 

%% Exercise 2
%
% Objective: Compare Heun with exact solution
%
% Details:  Consider the system of ODEs
%
%  |x1' = x1 / 2 - 2 x2|
%  |x2' = 5 x1 - x2 |
%
% with initial condition |x(0)=(1,1)|.
%
% Use your method from Exercise 1 to approximate the solution from |t=0|
% to |t=4*pi| with step size |h=0.05|.
%
% Compute the exact solution (by hand), and plot both phase portraits on 
% the same figure for comparison.
%
% Your submission should show the construction of the inline function, the
% use of your Heun's method to obtain the solution, a construction of the 
% exact solution, and a plot showing both.  In the comments, include the 
% exact solution.
%
% Label your axes and include a legend.
  
f = @(t, x1, x2) x1/2 - 2*x2;
g = @(t, x1, x2) 5*x1 - x2; 
t0 = 0;
tN = 4*pi;
h = 0.05;
x0 = [1, 1];
IEM_soln = IEM_two(f1, f2, t0, tN,  x0, h);


tt = linspace(0, 4*pi, 100);
exact1 = 1/151*exp(-t./4).*(151.*cos((sqrt(151).*t)./4)-5.*sqrt(151).*sin(sqrt(151).*t./4));
exact2 = 1/151*exp(-t./4).*(17.*sqrt(151).*sin(sqrt(151).*t./4)+151.*cos(sqrt(151).*t./4));

% Phase portrait
figure(1)
hold on;
plot(exact1, exact2, 'b');
plot(IEM_soln.y(1, :), IEM_soln.y(2, :), 'xg', 'Markersize', 10);

xlabel('t');
ylabel('y');
legend('Exact Solution', 'IEM', 'Location','Best');
hold off;


%% Exercise 3
%
% Objective: Compare your method with Euler's Method (from |iode|).
%
% Details: Use |iode| to plot the solution for the same problem with the same
% step size as on Exercise 2.
%
% Compare your solution on exercise 2, the exact solution from exercise 2
% and the approximation using Euler's method.
%
% You do not need to reproduce all the code here. Simply make note of any 
% differences and plot the graph.

%% Saving Images in MATLAB
%
% To do the following exercises, you will need to know how to output 
% graphics from MATLAB.  Create a folder on your Desktop (or elsewhere) to 
% contain the files generated by these exercises.  Make this folder the 
% "Current Folder" in the left side of the main MATLAB window.  This will 
% ensure that the files output by MATLAB end up in the folder you created.
%
% To save an image of a phase portrait, use the following steps:
%
% 1. Get the phase portrait looking the way you want in the |iode| window.  
%
% 2. Leaving |iode| open, switch to the main MATLAB window.
%
% 3. Type the command |print -dpng -r300 'filename.png'| in the command 
% window.
%
% This command will create a PNG graphic called |filename.png| in the 
% current folder.  The |-dpng| option tells MATLAB to output the graphic in
% PNG format; MATLAB also allows output in other formats, such as BMP, EPS,
% PNG and SVG.  The |-r300| option tells MATLAB to set the resolution at 
% 300 dots per inch and can be adjusted if you wish.

% The two are the same an indistinguishable. 
% EM is less accurate because of many cycles are shown
% Once a slight deviation occurs, the error will build up and shoot off.

%% Exercise 4
%
% Objective: Analyze phase portraits.
%
% Details: Compile the results of the following exercises into a single
% document (e.g. using a word processor) and export it to |PDF| for
% submission on Blackboard. 
%
% For each of the first-order systems of ODEs 4.1 to 4.10 below, do the
% following exercises:
%
% (a) Find the equilibrium solution.
%
% (b) Generate a phase portrait for the system (centre the graph on the
% equilibrium point). Include a few trajectories.
%
% (c) Classify the equilibrium on asymptotical stability, and behaviour 
% (sink, source, saddle-point, spiral, center, proper node, improper node) 
% - check table 3.5.1 and figure 3.5.7.
% Classify also as for clockwise or counterclockwise movement, when relevant.
%
% (d) Compute the eigenvalues of the matrix (you do not need to show your
% calculations). Using the eigenvalues you computed, justify part (c).
%
% To avoid numerical error, you should use Runge-Kutta solver with a step
% size of |0.01|. Change the display parameters, if necessary, to best
% understand the phase portrait.
%
% 4.1. |dx/dt = [3 4; 5 4] x - [2 1; 1 3] [4; 5]|
%
% 4.2. |dx/dt = [-3 -4; -5 -4] x - [13; 19]|
%x
% 4.3. |dx/dt = [4  -2; 2 -1] x + [8; 4]|
%
% 4.4. |dx/dt = [-4  2; -2 1] x + [8; 4]|
%
% 4.5. |dx/dt = [0  -1; 1 -1] x + [1; 0]|
%
% 4.6. |dx/dt = [0  1; -1 1] x + [1; 0]|
%
% 4.7. |dx/dt = [-1  1; -5 1] x|
%
% 4.8. |dx/dt = [1  -1; 5 -1] x|
%
% 4.9. |dx/dt = [13  6; 3 20] x|
%
% 4.10. |dx/dt = [-13  -6; -3 -20] x|
%